#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : x265
Version  : x265.3.5
Release  : 1
URL      : https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.5.tar.gz
Source0  : https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.5.tar.gz
Summary  : H.265/HEVC video encoder
Group    : Development/Tools
License  : MIT
Requires: x265-bin = %{version}-%{release}
Requires: x265-lib = %{version}-%{release}
Requires: x265-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : nasm-bin
BuildRequires : numactl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
=================
x265 HEVC Encoder
=================
| **Read:** | Online `documentation <http://x265.readthedocs.org/en/default/>`_ | Developer `wiki <http://bitbucket.org/multicoreware/x265/wiki/>`_
| **Download:** | `releases <http://ftp.videolan.org/pub/videolan/x265/>`_
| **Interact:** | #x265 on freenode.irc.net | `x265-devel@videolan.org <http://mailman.videolan.org/listinfo/x265-devel>`_ | `Report an issue <https://bitbucket.org/multicoreware/x265/issues?status=new&status=open>`_

%package bin
Summary: bin components for the x265 package.
Group: Binaries
Requires: x265-license = %{version}-%{release}

%description bin
bin components for the x265 package.


%package dev
Summary: dev components for the x265 package.
Group: Development
Requires: x265-lib = %{version}-%{release}
Requires: x265-bin = %{version}-%{release}
Provides: x265-devel = %{version}-%{release}
Requires: x265 = %{version}-%{release}

%description dev
dev components for the x265 package.


%package lib
Summary: lib components for the x265 package.
Group: Libraries
Requires: x265-license = %{version}-%{release}

%description lib
lib components for the x265 package.


%package license
Summary: license components for the x265 package.
Group: Default

%description license
license components for the x265 package.


%prep
%setup -q -n x265_3.5
cd %{_builddir}/x265_3.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693337479
pushd source
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
popd

%install
export SOURCE_DATE_EPOCH=1693337479
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/x265
cp %{_builddir}/x265_3.5/source/dynamicHDR10/json11/LICENSE.txt %{buildroot}/usr/share/package-licenses/x265/d40d61b8fa8ecae46da12bd1fce4162af02cff8c || :
pushd source
pushd clr-build
%make_install
popd
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/x265

%files dev
%defattr(-,root,root,-)
/usr/include/x265.h
/usr/include/x265_config.h
/usr/lib64/libx265.so
/usr/lib64/pkgconfig/x265.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libx265.so.199

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/x265/d40d61b8fa8ecae46da12bd1fce4162af02cff8c
